### ISSUE TITLE
Make the entire template card clickable

### ISSUE THREAD

**Issue by dannyverp** [dannyverp/markdownprofile#11]
Currently the cards used to select the user's template are only clickable on the select button. There also isn't any hover effect on the card itself. The behaviour of the TemplateSelector component should be changed to have hover styling and to have the entire card be clickable.

**Comment by AnkitJuyal009** [comment]
I would like to contribute. I will make Pr on 1st October, just wanted to ask if you're talking about this card component
![image](https://user-images.githubusercontent.com/43692967/94412721-c1ea9d80-0197-11eb-9d59-20331fe0bae8.png)

**Comment by AnkitJuyal009** [comment]
Please assign this to me.

**Comment by dannyverp** [comment]
Hi Ankit, thanks for reaching out. That is indeed the card I meant. I've assigned the issue to you. If you need any assistance please let me know.

**Comment by AnkitJuyal009** [comment]
Hey! @dannyverp I just completed enhancing the card. Just wanted to know if you want to me to make a new branch and commit changes in it or i myself just commit in master branch?And ya there's a screenshot of card hover
![image](https://user-images.githubusercontent.com/43692967/94650078-9db3cb80-0313-11eb-8f16-92dea3456468.png)
And made the card clickable as well.

**Comment by dannyverp** [comment]
From a fork from master to master should be fine 😄

**Comment by AnkitJuyal009** [comment]
Hey! @dannyverp I've made my pull request.
Thanks for assigning me.

**Comment by dannyverp** [comment]
Hi @AnkitJuyal009, I've check the PR. I've added a suggested commit https://github.com/dannyverp/markdownprofile/pull/12/commits/31da4b20ac7c1828c8ac8b28fcb4d04d1288b891 adding the pointer style to the cursor. If you're ok with adding that commit in the PR I'll merge it :+1:

**Comment by AnkitJuyal009** [comment]
Sure @dannyverp I'll do it.

**Comment by dannyverp** [comment]
Merged and deployed, thank you! :+1:
