### ISSUE TITLE
Dynamic height card titles, images, authors and description for template selectors

### ISSUE THREAD

**Issue by dannyverp** [dannyverp/markdownprofile#19]
# Description
Currently, the selection card displays quite weirdly in terms of height. The height of the images is a fixed height which causes them to stretch. The description and title fields can also cause the card to not align properly. Ideally, each field in the card should be the same height compared to the other card. This way the titles, images, authors and descriptions will line up neatly with each other.

# Steps to reproduce
* Open the page on any resolution which displays two cards next to each other.
* Notice the difference in title, image, description and author heights.
* Notice the weird stretch in the images

# Screenshots

![image](https://user-images.githubusercontent.com/7555537/95132019-5daf7700-075f-11eb-9296-ef92e016892d.png)

**Comment by Pustur** [comment]
Hey, I'd like to work on this. Can you assign me?

**Comment by dannyverp** [comment]
It looks much better now, thank you for your contribution!
