### ISSUE TITLE
List contributors on site

### ISSUE THREAD

**Issue by dannyverp** [dannyverp/markdownprofile#21]
It would be nice to show those that have contributed to the project somewhere on the site. I was thinking of putting a section in the footer where the profile pictures of the contributors (retrieved from Github) would be shown.

**Comment by yashsk98** [comment]
Hi @dannyverp ,
I would like to take a shot at this. I am new to open source, and might need a little guidance. But this looks fun and doable. 
Thanks!

**Comment by dannyverp** [comment]
Hi @yashsk98, you're more than welcome to. If there's anything I can help you with feel free to mention me in the ticket! 👍

**Comment by pbteja1998** [comment]
Hey @dannyverp checkout https://allcontributors.org/docs/en/bot/overview

This is the standard bot that most of the open source projects use. Check. It out.

**Comment by yashsk98** [comment]
<img width="1192" alt="Screenshot 2020-10-07 at 6 15 04 PM" src="https://user-images.githubusercontent.com/39120484/95332539-31b00500-08c9-11eb-852d-40dd49a974be.png">
Hi @dannyverp! I've done a basic job to start with. I've built a new component called Contributors and have instantiated it within the Footer component. Hovering over an avatar displays the GitHub username and clicking on it redirects us to the GitHub profile of the contributor.

I have 2 questions:
1. There is also a Bot contributor (dependabot) that turns up from the api. How would you like the page to deal with the bot?
2. How should I position this component within Footers? What text should I add above it? I was thinking we could add this to the "Built with <3 by .." maybe.

Also let me know any feedback you have. Cheers!

**Comment by dannyverp** [comment]
Hi @yashsk98, that's looking great so far!

1) I think we don't really have another chose than to filter the dependabot from the results in the page. I'd be fine with having an array filter on the JSON returned by Github's API.
2) I would suggest to remove the all rights reserved from the footer and have the "build with <3" and then the icons there on the left. I think the icons could be about 10-20% smaller than their current size to make it look better in proportion with the rest of the footer.

Let me know what you think.

**Comment by yashsk98** [comment]
Hi @dannyverp , that was the feedback I was looking for. 
I've made the suitable changes and created a PR, as seen in this thread. Let me know if any further changes are required. I'll also modify the readme.md to reflect the changes.
Thanks!
