### ISSUE TITLE
📋 Add click-to-copy button for markdown

### ISSUE THREAD

**Issue by dannyverp** [dannyverp/markdownprofile#7]
For the generated code section to be more useful a copy-to-clipboard button should be added. In the generated section at the left top, a button should be added that copies the output markdown to the user's clipboard.

![image](https://user-images.githubusercontent.com/7555537/93396267-ac13d900-f877-11ea-820f-83821396dec2.png)

**Comment by anup-a** [comment]
Hey, shall I work on this? 

Initial Approach - fetch the innerText of the main tag of CodeResult  and then store in clipboard through clipboardAPI.

**Comment by dannyverp** [comment]
Hi! You're more than welcome to. If you need any help or if you have any further suggestions let me know. The initial approach sounds great.

**Comment by anup-a** [comment]
check this out - https://github.com/dannyverp/markdownprofile/pull/9
