### ISSUE TITLE
🐞Grammerly causes page overvlow

### ISSUE THREAD

**Issue by dannyverp** [dannyverp/markdownprofile#8]
**Description:**
When using the profile generator and changing the description the page starts overflowing if the Grammarly browser plugin is used.

**Device:**
_Browser:_ Chrome version 84.0.4147.125 (64-bit) (Engine: Blink) 
_Operating system:_ Ubuntu 20.04.1 LTS

**Steps to reproduce:**
* Open https://markdownprofile.com/
* Edit the description
* Scroll down to the end of the page
* Scroll to infinity and beyond 🚀

![image](https://user-images.githubusercontent.com/7555537/93396353-cc439800-f877-11ea-9653-862ea315007e.png)

**Comment by ramadis** [comment]
I can work on this one if that's okay!

**Comment by dannyverp** [comment]
Hi @ramadis, thanks for your contibution and good to learn that this can resolve issues like this!
